### ISSUE TITLE
Adding `This is Learning` conference to the homepage

### ISSUE THREAD

**Issue by Haimantika** [this-is-learning/this-is-learning-website#18]
[The conference](https://til-conf.netlify.app/) was great, with amazing speakers. It would be great to have it added to the main homepage of https://thisislearning.dev/.

**Comment by Haimantika** [comment]
Happy to contribute, if this is considered as a valid issue.

**Comment by santoshyadavdev** [comment]
Hey @Haimantika , 

sure it will be useful for sure.

**Comment by Haimantika** [comment]
> Hey @Haimantika ,
> 
> sure it will be useful for sure.

Hi @santoshyadavdev thanks for assigning me. I have listed the conference. While running locally, the html file looked fine. However I was not able to run angular locally. If there is any other way for me to check, or if you can help, that would be great!

**Comment by santoshyadavdev** [comment]
Merged the PR, we have CI/CD in place
